<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE queries [
<!ELEMENT queries (query*)>
<!ELEMENT query (use-case+, description,paginacao?,command+, projecao?, ordenacoes?)>
<!ELEMENT use-case    (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT command     (#PCDATA) >
<!ELEMENT parametros  (#PCDATA) >
<!ELEMENT projecao (#PCDATA) >
<!ELEMENT paginar  (#PCDATA) >
<!ELEMENT paginacao (#PCDATA) >
<!ELEMENT colunaCodigo    (#PCDATA) >
<!ELEMENT colunaDescricao    (#PCDATA) >
<!ELEMENT numeroOcorrenciasPorPagina    (#PCDATA) >
<!ELEMENT primeiraCondicao    (#PCDATA) >
<!ELEMENT ascendente    (#PCDATA) >
<!ELEMENT ordenacoes (ordenacao+)>
<!ELEMENT ordenacao (#PCDATA)>

<!ELEMENT sql  (#PCDATA) >

<!ATTLIST ordenacao chave CDATA    #REQUIRED >
<!ATTLIST ordenacao default CDATA    #IMPLIED >

<!ATTLIST command parametros CDATA    #IMPLIED  >
<!ATTLIST command paginar CDATA    #IMPLIED  >

<!ATTLIST use-case name CDATA    #REQUIRED >

<!ATTLIST query name CDATA    #REQUIRED >

<!ATTLIST paginacao colunaCodigo CDATA    #REQUIRED>
<!ATTLIST paginacao colunaDescricao CDATA    #REQUIRED>
<!ATTLIST paginacao numeroOcorrenciasPorPagina CDATA    #REQUIRED>
<!ATTLIST paginacao primeiraCondicao CDATA    #REQUIRED>
<!ATTLIST paginacao ascendente CDATA    #REQUIRED>
<!ATTLIST paginacao hint CDATA    #REQUIRED>
<!ATTLIST paginacao hintAuxiliar CDATA   #IMPLIED >
]>

<queries>	

<query name="OBTERCONTACAPITAL">
	<use-case name="OBTERCONTACAPITAL"></use-case>
	<description>Consulta a Entidade Conta Capital por Matricula ou Cliente</description>
	<command>
		<![CDATA[
			FROM br.com.sicoob.sisbr.cca.legado.negocio.entidades.ContaCapitalLegado cca
			WHERE 1 = 1	
			<j:if test="${criterios.filtro != null}">
				<j:if test="${criterios.filtro.id != null}">
					AND cca.id = ${criterios.filtro.id}
				</j:if>
				<j:if test="${criterios.filtro.numCliente != null}">
					AND cca.numCliente = ${criterios.filtro.numCliente}
				</j:if>
			</j:if>			
		]]>
	</command>
</query>

<query name="OBTERLANCAMENTOSCCAPITAL">
	<use-case name="OBTERLANCAMENTOSCCAPITAL"></use-case>
	<description>Consulta a Entidade Lancamentosccapital</description>
	<command>
		<![CDATA[
			FROM br.com.sicoob.sisbr.cca.legado.negocio.entidades.LancamentosCCapitalLegado l
			WHERE 1 = 1	
			<j:if test="${criterios.filtro != null}">
				<j:if test="${criterios.filtro.lancamentosCCapitalLegadoPK.capaLoteCapitalLegado.capaLoteCapitalLegadoPK.dataLote != null}">
					AND l.lancamentosCCapitalLegadoPK.capaLoteCapitalLegado.capaLoteCapitalLegadoPK.dataLote = <bancoob:valorOql valor="${criterios.filtro.lancamentosCCapitalLegadoPK.capaLoteCapitalLegado.capaLoteCapitalLegadoPK.dataLote}" tipo="DateTimeDB" /> 
				</j:if>
				<j:if test="${criterios.filtro.lancamentosCCapitalLegadoPK.capaLoteCapitalLegado.capaLoteCapitalLegadoPK.numLoteLanc != null}">
					AND l.lancamentosCCapitalLegadoPK.capaLoteCapitalLegado.capaLoteCapitalLegadoPK.numLoteLanc = <bancoob:valorOql valor="${criterios.filtro.lancamentosCCapitalLegadoPK.capaLoteCapitalLegado.capaLoteCapitalLegadoPK.numLoteLanc}" tipo="Integer" />					
				</j:if>
				<j:if test="${criterios.filtro.lancamentosCCapitalLegadoPK.numSeqLanc != null}">
					AND l.lancamentosCCapitalLegadoPK.numSeqLanc = <bancoob:valorOql valor="${criterios.filtro.lancamentosCCapitalLegadoPK.numSeqLanc}" tipo="Integer" />
				</j:if>				
				<j:if test="${criterios.filtro.iDTipoHistoricoLanc != null}">
					AND l.iDTipoHistoricoLanc = <bancoob:valorOql valor="${criterios.filtro.iDTipoHistoricoLanc}" tipo="Integer" />
				</j:if>
				<j:if test="${criterios.filtro.contaCapitalLegado.numMatricula != null}">
					AND l.contaCapitalLegado.numMatricula = <bancoob:valorOql valor="${criterios.filtro.contaCapitalLegado.numMatricula}" tipo="Integer" />
				</j:if>				
				<j:if test="${criterios.filtro.descOperacaoExterna != null}">
					AND l.descOperacaoExterna = <bancoob:valorOql valor="${criterios.filtro.descOperacaoExterna}" tipo="String" />
				</j:if>	
			</j:if>			
		]]>
	</command>
</query>

<query name="OBTERULTIMAMATRICULA">
	<use-case name="OBTERULTIMAMATRICULA"></use-case>
	<description>Retorna a ultima matricula da entidade conta capital</description>
	<command>
		<![CDATA[
			select isnull(max(cca.numMatricula),0) FROM ContaCapital cca
		]]>
	</command>
</query>


<query name="OBTERULTIMONUMSEQLANC">
	<use-case name="OBTERULTIMONUMSEQLANC"></use-case>
	<description>Retorna a ultimo seqlanc</description>
	<command>
		<![CDATA[
				SELECT isnull(max(l.lancamentosCCapitalLegadoPK.numSeqLanc),0)
				FROM br.com.sicoob.sisbr.cca.legado.negocio.entidades.LancamentosCCapitalLegado l					 
				WHERE l.lancamentosCCapitalLegadoPK.capaLoteCapitalLegado.capaLoteCapitalLegadoPK.dataLote = :dataLote
				AND l.lancamentosCCapitalLegadoPK.capaLoteCapitalLegado.capaLoteCapitalLegadoPK.numLoteLanc = :numLoteLanc
		]]>
	</command>
</query>

<query name="OBTERDADOSTRABALHA">
	<use-case name="OBTERDADOSTRABALHA"></use-case>
	<description>Consulta os dados da Tabela Trabalha filtrando por pessoa fisica</description>
	<command>
		<![CDATA[

		SELECT 
			T.UIDTrabalha,
			T.DescMatriculaFunc,
			T.DescEmpresaTrabalha,
			T.DescOcupacaoProfissional,
			T.DataAdmissao,
			T.NumPessoaFisica,
			T.NumPessoaJuridica
		FROM 
			dbo.Trabalha T 
			INNER Join dbo.LancFolhaPJ LF On 
				T.NumPessoaJuridica = LF.NumPessoaJuridica 
			Left Join OrgaoLancFolha Org on
				Org.NumPessoaJuridica = T.NumPessoaJuridica And 
				Org.CodOrgao = T.CodOrgao 
			LEFT JOIN dbo.Pessoa PJur ON
				PJur.NumPessoa = T.NumPessoaJuridica
			WHERE 
			T.NumPessoaFisica = ${numPessoa} AND 
			DescMatriculaFunc IS NOT NULL AND 
			T.NumPessoaJuridica IS NOT NULL AND
			T.CodSitFuncionario = 0
		]]>
	</command>
</query>

<query name="OBTERDADOSTRABALHAMATRICULA">
	<use-case name="OBTERDADOSTRABALHAMATRICULA"></use-case>
	<description>Consulta os dados da Tabela Trabalha filtrando por matricula</description>
	<command>
		<![CDATA[

		SELECT 
			T.UIDTrabalha,
			T.DescMatriculaFunc,
			T.DescEmpresaTrabalha,
			T.DescOcupacaoProfissional,
			T.DataAdmissao,
			T.NumPessoaFisica,
			T.NumPessoaJuridica
		FROM 
			dbo.Trabalha T 
			INNER Join dbo.LancFolhaPJ LF On 
				T.NumPessoaJuridica = LF.NumPessoaJuridica 
			Left Join OrgaoLancFolha Org on
				Org.NumPessoaJuridica = T.NumPessoaJuridica And 
				Org.CodOrgao = T.CodOrgao 
			LEFT JOIN dbo.Pessoa PJur ON
				PJur.NumPessoa = T.NumPessoaJuridica
			WHERE 
			T.DescMatriculaFunc = '${descMatriculaFunc}' AND 
			DescMatriculaFunc IS NOT NULL AND 
			T.NumPessoaJuridica IS NOT NULL AND
			T.CodSitFuncionario = 0
		]]>
	</command>
</query>

<query name="OBTERDADOSVALORCOTAS">
	<use-case name="OBTERDADOSVALORCOTAS"></use-case>
	<description>Consulta o valor da ultima cota cadastrada e numero minimo de cotas obrigatorias para o conta capital</description>
	<command>
		<![CDATA[
			SELECT TOP 1 ValorCota, NumMinCotasInteg 
			From dbo.ValorCotas 
			WHERE DataInicialCota &lt;= Convert(DateTime, GetDate(), 102)
			ORDER BY DataInicialCota DESC 			
		]]>
	</command>
</query>


<query name="OBTERDADOSCONCILIACAOCONTABIL">
	<use-case name="OBTERDADOSCONCILIACAOCONTABIL"></use-case>
	<description>Consulta os dados da conciliacao contabil</description>
	<command>
		<![CDATA[
			SELECT 
				DataProduto AS DataContabilizacao,
				NumContaBACEN,
				ValorSaldo AS SaldoTotal
			FROM 
				ConciliacaoContabilCCA WITH (NOLOCK)
			WHERE 
				BolProcessado = 0	
		]]>
	</command>
</query>
<query name="ATUALIZARCONCILIACAOCONTABIL">
	<use-case name="ATUALIZARCONCILIACAOCONTABIL"></use-case>
	<description>ATUALIZARCONCILIACAOCONTABIL</description>	
	<command>
		<![CDATA[
			UPDATE  
				ConciliacaoContabilCCA 
			SET BolProcessado = 1 
			WHERE DataProduto = '${dataContabilizacao}' AND NumContaBACEN = '${numContaBACEN}'
		]]>
	</command>
</query>
<query name="OBTERSALDOCAPITALSINGULARES">
	<use-case name="OBTERSALDOCAPITALSINGULARES"></use-case>
	<description>Consulta o saldo capital das singulares nas centrais e dos clientes nao cooperativas que sao da central</description>
	<command>
		<![CDATA[
			SELECT c.NumCooperativa as numCoop, numAnoRef, numMesRef, sum(i.valoracumulado) as valor
				FROM infacumulada i
					INNER JOIN pessoa p on p.NumPessoa = i.NumCliente
					INNER JOIN cooperativa c on c.NumCNPJ = p.NumCGC_CPF 
				WHERE idproduto = 2 
					AND NumAnoRef = ${anoReferencia}
					AND NumMesRef = ${mesReferencia}
					AND c.numCooperativa in (${numCooperativas}) 
					AND c.numPac = 0
					AND IDTipoInfoAcumulo = 6
				GROUP BY c.NumCooperativa, NumAnoRef, NumMesRef
				UNION
				SELECT c.NumCooperativa as numCoop, numAnoRef, numMesRef, sum(i.valoracumulado) as valor
				FROM infacumulada i
					INNER JOIN pessoa p on p.NumPessoa = i.NumCliente
					LEFT JOIN cooperativa c on c.NumCNPJ = p.NumCGC_CPF 
				WHERE idproduto = 2 
					AND NumAnoRef = ${anoReferencia}
					AND NumMesRef = ${mesReferencia}
					AND IDTipoInfoAcumulo = 6
					AND c.numCooperativa IS NULL					
				GROUP BY c.NumCooperativa, NumAnoRef, NumMesRef				
		]]>
	</command>
</query>

	<query name="OBTERSNAPSHOTSINGULARES">
		<use-case name="OBTERSNAPSHOTSINGULARES"></use-case>
		<description>Consulta snapshot das singulares pela central</description>
		<command>
			<![CDATA[
				SELECT c.NumCooperativa as numCoop
					FROM pessoa p 
					INNER JOIN cooperativa c on c.NumCNPJ = p.NumCGC_CPF 
					INNER JOIN InfAcumulada i on p.NumPessoa = i.NumCliente
					WHERE c.numCoopPai = ${numCoopCentral} 
						AND c.numPac = 0
						AND i.NumAnoRef = ${anoReferencia}
						AND i.NumMesRef = ${mesReferencia}
						AND i.IDTipoInfoAcumulo = 6
						AND idproduto = 2 
			]]>
		</command>
	</query>

	<query name="GERAR_REL_FICHA_MATRIC">
		<use-case name="Gerar relatorio ficha Matricula"></use-case>
		<description>Obter dados ficha Matricula</description>
		<command>
			<![CDATA[
				SELECT ContaCapital.ValorSaldoAtuInteg, ValorLancInteg = (SELECT ValorLanc = SUM(V.ValorLanc) FROM dbo.Viw_CCA_Extrato AS V WHERE V.NumMatricula = ContaCapital.NumMatricula AND  V.CodGrupoHist = ${COD_GRUPO_HIST_INTEGRALIZACAO} And V.BolAtualizado = 0 GROUP BY V.NumMatricula),  
					ContaCapital.ValorSaldoAtuSubsc, ValorLancSubsc = (SELECT ValorLanc = SUM(V.ValorLanc) FROM dbo.Viw_CCA_Extrato AS V WHERE V.NumMatricula = ContaCapital.NumMatricula AND  V.CodGrupoHist = ${COD_GRUPO_HIST_SUBSCRICAO} And V.BolAtualizado = 0 GROUP BY V.NumMatricula),  
					Pessoa.DescNomePessoa,   PessoaFisica.DataNascimento, PessoaFisica.DescNacionalidade,  
					PessoaFisica.DescNaturalidade, PessoaFisica.NumRG, PessoaFisica.DescOrgaoExpRG,  
					PessoaFisica.DescUfOrgExpRG, PessoaFisica.DataEmissaoRG, PessoaFisica.CodEstadoCivil,  
					PessoaFisica.CodTipoSexo, PessoaFisica.codprofissao, ListaItem.desclistaitem, EnderecoPessoa.CodTipoEndereco,  
					EnderecoResidencial = (ISNULL(tl.DescLogradouro, '') +' '+ (SELECT TOP 1 DescEndereco + CASE ISNULL(DescNumero, '') WHEN '' THEN '' ELSE ' ' + DescNumero END + CASE ISNULL(DescComplemento, '') WHEN '' THEN '' ELSE ' ' + DescComplemento END FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa )) ,  
					BairroResidencial=(SELECT TOP 1 NomeBairro FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa ),  
					CidadeResidencial= (SELECT TOP 1 NomeCidade FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa ),  
					UFResidencial=(SELECT TOP 1 DescUF FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa ),  
					CepResidencial=(SELECT TOP 1 SUBSTRING(RIGHT('00000000' + LTRIM(Str(NumCep)),8),1,2)  + '.' + SUBSTRING(RIGHT('00000000' + LTRIM(Str(NumCEP)),8),3,3)  + '-' + SUBSTRING(RIGHT('00000000' + LTRIM(Str(NumCEP)),8),6,8) FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa ),  
					DDDResidencial =(SELECT TOP 1 NumDDD FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa ),  
					NumTelefoneResidencial = (SELECT TOP 1 NumTelefone FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa ),  
					RamalResidencial = (SELECT TOP 1 NumRamal FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa ),  
					EnderecoComercial = (SELECT TOP 1 DescEndereco + CASE ISNULL(DescNumero, '') WHEN '' THEN '' ELSE ' ' + DescNumero END + CASE ISNULL(DescComplemento, '') WHEN '' THEN '' ELSE ' ' + DescComplemento END FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=1 and NumPessoa = Pessoa.NumPessoa ),  
					BairroComercial=(SELECT TOP 1 NomeBairro FROM dbo.EnderecoPessoa WHERE CodtipoEndereco=1 and NumPessoa = Pessoa.NumPessoa ),  
					CidadeComercial= (SELECT TOP 1 NomeCidade FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=1 and numpessoa = Pessoa.NumPessoa ),  
					UFComercial=(SELECT TOP 1 DescUF FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=1 and numpessoa = Pessoa.NumPessoa ),  
					CepComercial=(SELECT TOP 1 SUBSTRING(RIGHT('00000000' + LTrim(STR(NumCep)),8),1,2)  + '.' + SUBSTRING(RIGHT('00000000' + LTRIM(Str(NumCEP)),8),3,3)  + '-' + SUBSTRING(RIGHT('00000000' + LTRIM(Str(NumCEP)),8),6,8) FROM dbo.EnderecoPessoa WHERE CodTipoEndereco=1 and NumPessoa = Pessoa.NumPessoa),  
					DDDComercial =(SELECT TOP 1 NumDDD FROM dbo.EnderecoPessoa WHERE CodTipoEndereco = 1 and NumPessoa = Pessoa.NumPessoa),  
					NumTelefoneComercial = (SELECT TOP 1 NumTelefone FROM dbo.EnderecoPessoa WHERE CodTipoEndereco = 1 and NumPessoa = Pessoa.NumPessoa),  
					Ramalcomercial = (SELECT TOP 1 NumRamal FROM dbo.EnderecoPessoa WHERE CodTipoEndereco = 1 and NumPessoa = Pessoa.NumPessoa), 
					EnderecoPessoa.BolEnvioCorrespondencia, Pessoa.DescApelidoPessoa,  
					NumCGC_CPF = CASE CodPF_PJ  WHEN ${COD_TIPO_PES_FISICA} THEN  SUBSTRING(NumCGC_CPF,1,3) + '.' + SUBSTRING(NumCGC_CPF,4,3) + '.' + SUBSTRING(NumCGC_CPF,7,3) + '-' + SUBSTRING(NumCGC_CPF,10,2)  WHEN  ${COD_TIPO_PES_JURIDICA} THEN  SUBSTRING(NumCGC_CPF,1,2) + '.' + SUBSTRING(NumCGC_CPF,3,3) + '.' + SUBSTRING(NumCGC_CPF,6,3) + '/' + SUBSTRING(NumCGC_CPF,9,4) + '-' + SUBSTRING(NumCGC_CPF,13,2) END,  
					Pessoa.NumPessoa,  sNumPessoa = CASE LEN(CONVERT(CHAR(10),Pessoa.Numpessoa)) WHEN 0 THEN  RTRIM(CONVERT(CHAR(10),Pessoa.NumPessoa)) ELSE  RTRIM(left(CONVERT(CHAR(10),Pessoa.NumPessoa), LEN(RTRIM(CONVERT(CHAR(10),pessoa.NumPessoa)))-1) + '-' +  RIGHT(RTRIM(CONVERT(CHAR(10),Pessoa.numPessoa)),1)) END,  
					PessoaJuridica.NumInscEstadual, PessoaJuridica.DataConstituicao, Pessoa.CodPF_PJ,  
					ParcelamentoCCA.NumParcelamento, ParcelamentoCCA.NumParcela, ParcelamentoCCA.DataVencParcela, ParcelamentoCCA.ValorParcela,  
					ModoLanc = CASE ParcelamentoCCA.CodModoLanc  
						WHEN ${COD_MODO_LANCAMENTO_VIA_CAIXA} THEN CONVERT(VARCHAR(40), 'Via Caixa')  
						WHEN ${COD_MODO_LANCAMENTO_VIA_FOLHA} THEN CONVERT(VARCHAR(40), 'Via Folha' +  
									CASE WHEN ParcelamentoCCA.UIDTrabalha IS NULL THEN '' 
									Else ': ' + (SELECT DescMatriculaFunc FROM dbo.Trabalha WHERE Trabalha.UIDTrabalha = ParcelamentoCCA.UIDTrabalha) 
									END)  
						WHEN ${COD_MODO_LANCAMENTO_VIA_COBRANCA} THEN CONVERT(VARCHAR(40), 'Via Cobrança')  
						WHEN ${COD_MODO_LANCAMENTO_VIA_MIGRACAO} THEN CONVERT(VARCHAR(40), 'Via Migração')  
						WHEN ${COD_MODO_LANCAMENTO_VIA_BANCO_CHADMIN} THEN CONVERT(VARCHAR(40), 'Via Banco/Chq. Adm.')  
						WHEN ${COD_MODO_LANCAMENTO_VIA_RATEIO} THEN CONVERT(VARCHAR(40), 'Via Rateio')  
						WHEN ${COD_MODO_LANCAMENTO_VIA_RESERVA} THEN CONVERT(VARCHAR(40), 'Via Reserva')  
						WHEN ${COD_MODO_LANCAMENTO_VIA_CONTA} THEN  
						   CASE WHEN LEN(LTRIM(STR(ParcelamentoCCA.NumContaCorrente))) &lt; 5 THEN  CONVERT(VARCHAR(40), 'Via Conta Corrente: ' + SUBSTRING(STR(ParcelamentoCCA.NumContaCorrente), 7, 3) + '-' + SUBSTRING(STR(ParcelamentoCCA.NumContaCorrente), 10, 1) )  
								WHEN LEN(LTRIM(STR(ParcelamentoCCA.NumContaCorrente))) &gt; 4 AND LEN(LTRIM(STR(ParcelamentoCCA.NumContaCorrente))) &lt; 8 THEN CONVERT(VARCHAR(40), 'Via Conta Corrente: ' + SUBSTRING(STR(ParcelamentoCCA.NumContaCorrente), 4, 3) + '.' + SUBSTRING(STR(ParcelamentoCCA.NumContaCorrente), 7, 3) + '-' + SUBSTRING(STR(ParcelamentoCCA.NumContaCorrente), 10, 1) )  
						ELSE CONVERT(VARCHAR(40), 'Via Conta Corrente: ' + SUBSTRING(STR(ParcelamentoCCA.NumContaCorrente), 1, 3) + '.' + SUBSTRING(STR(ParcelamentoCCA.NumContaCorrente), 4, 3) + '.' + SUBSTRING(STR(ParcelamentoCCA.NumContaCorrente), 7, 3) + '-' + SUBSTRING(STR(ParcelamentoCCA.NumContaCorrente), 10, 1) ) END END,
					Situacao = CASE ParcelamentoCCA.CodSituacaoParcela  
						WHEN ${COD_PARCELA_GERADA} THEN CONVERT(VARCHAR(30), 'Em Aberto')  
						WHEN ${COD_PARCELA_PAGA_VIA_CAIXA} THEN CONVERT(VARCHAR(30), 'Paga Via Caixa')  
						WHEN ${COD_PARCELA_PAGA_VIA_CONTA} THEN CONVERT(VARCHAR(30), 'Paga Via Conta')  
						WHEN ${COD_PARCELA_CANCELADA} THEN CONVERT(VARCHAR(30), 'Cancelada')  
						WHEN ${COD_PARCELA_PAGA_VIA_CHADMIN} THEN CONVERT(VARCHAR(30), 'Paga Via Ch. Admin.')  
						WHEN ${COD_PARCELA_EXCLUIDA} THEN CONVERT(VARCHAR(30), 'Excluída')  
						WHEN ${COD_PARCELA_PAGA_VIA_FOLHA} THEN CONVERT(VARCHAR(30), 'Paga Via Folha')  
						WHEN ${COD_PARCELA_PAGA_VIA_COBRANCA} THEN CONVERT(VARCHAR(30), 'Paga Via Cobrança') 
						WHEN ${COD_PARCELA_PAGA_VIA_RATEIO} THEN CONVERT(VARCHAR(30), 'Paga Via Rateio') 
						WHEN ${COD_PARCELA_PAGA_VIA_RESERVA} THEN CONVERT(VARCHAR(30), 'Paga Via Reserva') 
						WHEN ${COD_PARCELA_PAGA_ANTES_MIGRACAO} THEN CONVERT(VARCHAR(30), 'Paga Antes da Migração') END  
					,CondicaoAssociacao.DescCondicaoAssociacao,
					ISNULL(EC.DESCLISTAITEM, '') AS descEstadoCivil
		
				FROM dbo.ContaCapital  
					LEFT JOIN dbo.ParcelamentoCCA ON ContaCapital.NumMatricula = ParcelamentoCCA.NumMatricula AND CodTipoParcelamento = 1  
					INNER JOIN dbo.Pessoa ON Pessoa.NumPessoa = ContaCapital.NumCliente  
					INNER JOIN dbo.Cliente ON ContaCapital.NumCliente = Cliente.NumCliente  
					lEFT JOIN dbo.PessoaFisica ON Pessoa.NumPessoa = PessoaFisica.NumPessoa  
					INNER JOIN  dbo.EnderecoPessoa ON Pessoa.NumPessoa = EnderecoPessoa.NumPessoa
					LEFT JOIN dbo.TipoLogradouro AS tl ON EnderecoPessoa.IdTipoLogradouro = tl.IdTipoLogradouro 
					LEFT Join dbo.PessoaJuridica ON dbo.pessoa.NumPessoa = PessoaJuridica.NumPessoa  
					LEFT JOIN  dbo.CondicaoAssociacao ON ContaCapital.IDCondicaoAssociacao = CondicaoAssociacao.IDCondicaoAssociacao  
					LEFT JOIN dbo.listaitem on listaitem.idlista = ${LST_TIPO_PROFISSAO} and listaitem.codlistaitem = PessoaFisica.codprofissao
					LEFT JOIN dbo.ListaItem AS ec ON ec.IdLista = ${LST_TIPO_ESTADO_CIVIL} and ec.codlistaitem = PessoaFisica.CodEstadoCivil 
				WHERE dbo.ContaCapital.NumMatricula = ${matricula}
										  
				ORDER BY EnderecoPessoa.BolEnvioCorrespondencia, ParcelamentoCCA.NumParcelamento, ParcelamentoCCA.NumParcela

			]]>
		</command>
	</query>
	<query name="GERAR_REL_FICHA_ADMISSAO">
		<use-case name="Gerar relatorio ficha Admissao"></use-case>
		<description>Obter dados ficha Admissao</description>
		<command>
			<![CDATA[
				SELECT Pessoa.DescNomePessoa, PessoaFisica.DataNascimento, PessoaFisica.DescNacionalidade, 
						PessoaFisica.DescNaturalidade, PessoaFisica.NumRG, PessoaFisica.DescOrgaoExpRG, 
						PessoaFisica.DescUfOrgExpRG, PessoaFisica.DataEmissaoRG, PessoaFisica.CodEstadoCivil, 
						PessoaFisica.CodTipoSexo, PessoaFisica.codprofissao, ListaItem.desclistaitem, EnderecoPessoa.CodTipoEndereco, 
						EnderecoResidencial = (ISNULL(tl.DescLogradouro, '') +' '+ (Select top 1 DescEndereco + CASE ISNULL(DescNumero, '') WHEN '' THEN '' ELSE ' ' + DescNumero END + CASE ISNULL(DescComplemento, '') WHEN '' THEN '' ELSE ' ' + DescComplemento END From dbo.EnderecoPessoa Where CodTipoEndereco=0 and NumPessoa =Pessoa.NumPessoa )) , 
						BairroResidencial=(Select top 1 NomeBairro From dbo.EnderecoPessoa Where CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa), 
						CidadeResidencial= (Select top 1 NomeCidade From dbo.EnderecoPessoa Where CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa), 
						UFResidencial=(Select top 1 DescUF From dbo.EnderecoPessoa Where CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa), 
						CepResidencial=(Select top 1 SubString(Right('00000000' + LTrim(Str(NumCep)),8),1,2) + '.' + SubString(Right('00000000' + LTrim(Str(NumCEP)),8),3,3) + '-' + SubString(Right('00000000' + LTrim(Str(NumCEP)),8),6,8) From dbo.EnderecoPessoa Where CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa), 
						DDDResidencial =(Select top 1 NumDDD From dbo.EnderecoPessoa Where CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa), 
						NumTelefoneResidencial = (Select top 1 NumTelefone From dbo.EnderecoPessoa Where CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa), 
						RamalResidencial = (Select top 1 NumRamal From dbo.EnderecoPessoa Where CodTipoEndereco=0 and NumPessoa = Pessoa.NumPessoa), 
						EnderecoComercial = (Select top 1 DescEndereco + CASE ISNULL(DescNumero, '') WHEN '' THEN '' ELSE ' ' + DescNumero END + CASE ISNULL(DescComplemento, '') WHEN '' THEN '' ELSE ' ' + DescComplemento END From dbo.EnderecoPessoa Where CodTipoEndereco=1 and NumPessoa = Pessoa.NumPessoa) , 
						BairroComercial=(Select top 1 NomeBairro From dbo.EnderecoPessoa Where CodtipoEndereco=1 and NumPessoa = Pessoa.NumPessoa), 
						CidadeComercial= (Select top 1 NomeCidade From dbo.EnderecoPessoa Where CodTipoEndereco=1 and numpessoa = Pessoa.NumPessoa), 
						UFComercial=(Select top 1 DescUF From dbo.EnderecoPessoa Where CodTipoEndereco=1 and numpessoa = Pessoa.NumPessoa), 
						CepComercial=(Select top 1 SubString(Right('00000000' + LTrim(Str(NumCep)),8),1,2) + '.' + SubString(Right('00000000' + LTrim(Str(NumCEP)),8),3,3) + '-' + SubString(Right('00000000' + LTrim(Str(NumCEP)),8),6,8) From dbo.EnderecoPessoa Where CodTipoEndereco=1 and NumPessoa = Pessoa.NumPessoa), 
						DDDComercial =(Select top 1 NumDDD From dbo.EnderecoPessoa Where CodTipoEndereco=1 and NumPessoa = Pessoa.NumPessoa), 
						NumTelefoneComercial = (Select top 1 NumTelefone From dbo.EnderecoPessoa Where CodTipoEndereco=1 and NumPessoa = Pessoa.NumPessoa), 
						Ramalcomercial = (Select top 1 NumRamal From dbo.EnderecoPessoa Where CodTipoEndereco=1 and NumPessoa = Pessoa.NumPessoa), 
						EnderecoPessoa.BolEnvioCorrespondencia, Pessoa.DescApelidoPessoa, Pessoa.NumPessoa, 
						
						NumCGC_CPF = CASE CodPF_PJ 
										WHEN ${COD_TIPO_PES_FISICA} THEN SUBSTRING(NumCGC_CPF,1,3) + '.' + SUBSTRING(NumCGC_CPF,4,3) + '.' + SUBSTRING(NumCGC_CPF,7,3) + '-' + SUBSTRING(NumCGC_CPF,10,2) 
										WHEN ${COD_TIPO_PES_JURIDICA} THEN SUBSTRING(NumCGC_CPF,1,2) + '.' + SUBSTRING(NumCGC_CPF,3,3) + '.' + SUBSTRING(NumCGC_CPF,6,3) + '/' + SUBSTRING(NumCGC_CPF,9,4) + '-' + SUBSTRING(NumCGC_CPF,13,2) END, 
						sNumPessoa = CASE LEN(convert(char(10),Pessoa.Numpessoa)) 
											WHEN 0 THEN RTRIM(convert(char(10),Pessoa.NumPessoa)) 
											ELSE RTRIM(left(convert(char(10),Pessoa.NumPessoa), LEN(RTRIM(convert(char(10),pessoa.NumPessoa)))-1) + '-' + RIGHT(RTRIM(convert(char(10),Pessoa.numPessoa)),1)) END, 
						PessoaJuridica.NumInscEstadual, PessoaJuridica.DataConstituicao, Pessoa.CodPF_PJ 
						, CondicaoAssociacao.DescCondicaoAssociacao,
						ISNULL(EC.DESCLISTAITEM, '') AS descEstadoCivil
					FROM dbo.Pessoa 
						INNER JOIN dbo.Cliente ON Pessoa.NumPessoa = Cliente.NumCliente 
						LEFT JOIN dbo.PessoaFisica ON Pessoa.NumPessoa = PessoaFisica.NumPessoa 
						INNER JOIN dbo.EnderecoPessoa ON Pessoa.NumPessoa = EnderecoPessoa.NumPessoa 
						LEFT JOIN dbo.TipoLogradouro AS tl ON EnderecoPessoa.IdTipoLogradouro = tl.IdTipoLogradouro
						LEFT JOIN dbo.PessoaJuridica on dbo.pessoa.NumPessoa =PessoaJuridica.NumPessoa 
						LEFT JOIN dbo.CondicaoAssociacao ON CodAplicacaoPessoa = Pessoa.CodPF_PJ OR CodAplicacaoPessoa = ${COD_TIPO_AMBAS}
						LEFT JOIN dbo.listaitem on listaitem.idlista = ${LST_TIPO_PROFISSAO} and listaitem.codlistaitem = PessoaFisica.codprofissao 
						LEFT JOIN dbo.ListaItem AS ec ON ec.IdLista = ${LST_TIPO_ESTADO_CIVIL} and ec.codlistaitem = PessoaFisica.CodEstadoCivil  
					WHERE Pessoa.NumPessoa = ${numPessoa}
					 AND CondicaoAssociacao.CodAplicacaoCooperativa &gt; ${iAplicCoopDif}
					ORDER BY EnderecoPessoa.BolEnvioCorrespondencia 
			]]>
		</command>
	</query>
		
	<query name="INCLUIROPERACAOFINANCEIRA">
		<use-case name="INCLUIROPERACAOFINANCEIRA"></use-case>
		<description>Inclui operacao financeira</description>
		<command>
			<![CDATA[
				
				INSERT INTO dbo.OperacaoFinanceira 
				(
					IDOpFinanceira, IDOperacao, IDProduto, DataOpFinanceira, DataProcessamento, CodStatusOpFin, CodTipoMovimento, CodSubRelCont, CodTipoContabilizacao,
					BolContabilizaCoop, BolOpProcessada, NumPac, NumCoopRecebedora, NumCliente,IDModalidadeProduto
				) 
				VALUES 
				(
					${operacaoFinanceira.idOperacaoFinanceira}, ${operacaoFinanceira.idOperacao}, ${operacaoFinanceira.idProduto}, '${operacaoFinanceira.dataOpFinanceiraFormatado}',
					'${operacaoFinanceira.dataProcessamentoFormatado}', ${operacaoFinanceira.codStatusOpFin}, ${operacaoFinanceira.codTipoMovimento}, 
					${operacaoFinanceira.codSubRelCont}, ${operacaoFinanceira.codTipoContabilizacao}, ${operacaoFinanceira.BolContabilizaCoop},
					${operacaoFinanceira.bolOpProcessada}, ${operacaoFinanceira.numPac}, ${operacaoFinanceira.numCoopRecebedora}, 
					<j:if test="${operacaoFinanceira.numCliente != null}">
						${operacaoFinanceira.numCliente}
					</j:if>
					<j:if test="${operacaoFinanceira.numCliente == null}">
						NULL
					</j:if>,
					${operacaoFinanceira.idModalidadeProduto}		
				)
			]]>
		</command>
	</query>
	
	<query name="INCLUIRVALOROPERACAOFINANCEIRA">
		<use-case name="INCLUIROPERACAOFINANCEIRA"></use-case>
		<description>Inclui operacao financeira</description>
		<command>
			<![CDATA[
				INSERT INTO dbo.ValorOpFin 
				(
					IDOpFinanceira, IDTipoValorCont, IDProduto, ValorArgumento
				) 
				VALUES 
				(
					${operacaoFinanceira.idOperacaoFinanceira}, ${operacaoFinanceira.idTipoValorCont}, ${operacaoFinanceira.idProduto}, ${operacaoFinanceira.valor}
				)
			]]>
		</command>
	</query>
	
	<query name="CONSULTARCLIENTECOOPERATIVA">
		<use-case name="CONSULTARCLIENTECOOPERATIVA"></use-case>
		<description>Consulta cliente por cooperativa</description>
		<command>
			<![CDATA[
				SELECT 
					p.numpessoa as numcliente 
				FROM 
					Cooperativa c
					INNER JOIN Pessoa p on c.NumCNPJ = p.NumCGC_CPF
					INNER JOIN Cliente cli on cli.Numcliente = p.numpessoa
				WHERE 
					c.numcooperativa = ${numCoop}
					and c.NumPac = ${numPac}					
			]]>
		</command>
	</query>
	
	<query name="ULTIMOIDOPERACAOFINANCEIRA">
		<use-case name="ULTIMOIDOPERACAOFINANCEIRA"></use-case>
		<description>Consulta ultimo id</description>
		<command>
			<![CDATA[
				SELECT MAX(IDOpFinanceira) as IDOpFinanceira FROM dbo.OperacaoFinanceira
			]]>
		</command>
	</query>
	
	<query name="VALORESTORNOPARTINDIRETA">
		<use-case name="VALORESTORNOPARTINDIRETA"></use-case>
		<description>VALORESTORNOPARTINDIRETA</description>		
		<command>
			<![CDATA[
				SELECT 
				       TOP 1 
				       ISNULL(VOP.ValorArgumento,0) ValorEstorno
				FROM 
				       dbo.OperacaoFinanceira OPF with (nolock)
				       INNER JOIN dbo.ValorOpFin VOP with (nolock) ON OPF.IDOpFinanceira = VOP.IDOpFinanceira
				WHERE 
				       OPF.IDProduto = ${idProduto} 
				       AND OPF.IDOperacao = ${idOperacao}
				       AND OPF.DataProcessamento BETWEEN '${dataPrimeiroFechamento}' AND getdate()
				       AND OPF.CodStatusOpFin = ${codStatusOpFin}
				       AND VOP.IDTipoValorCont = ${idTipoValorCont}
				ORDER BY 
				       OPF.IDOpFinanceira DESC
				       
			]]>
		</command>
	</query>
	
	<query name="VERIFICASEDEBINDFOLHACLIENTE">
		<use-case name="VERIFICASEDEBINDFOLHACLIENTE"></use-case>
		<description>Verifica se o cliente informado tiver débito indeterminado via folha cadastrado</description>
		<command>
			<![CDATA[
			
				SELECT CC.NumMatricula  
				FROM dbo.ContaCapital  CC
				WHERE CC.BolDebIndeterminado = 1 
				AND CC.CodSituacao = 1 
				AND CC.CodFormadeb in ( ${COD_MODO_LANCAMENTO_VIA_FOLHA}, ${COD_MODO_LANCAMENTO_VIA_BANCO_CHADMIN} )  
				<j:if test="${numCliente != null}">				
					AND CC.NumCliente =  ${numCliente}
				</j:if>
				<j:if test="${NumMatricula != null}">				
					AND CC.NumMatricula != ${numMatricula}
					AND CC.NumCliente in (SELECT NumCliente FROM dbo.ContaCapital WHERE NumMatricula = ${numMatricula}) 
				</j:if>
							
			]]>
		</command>
	</query>
		
	<query name="VERIFICARPARCELAVIAFOLHACLIENTE">
		<use-case name="VERIFICARPARCELAVIAFOLHACLIENTE"></use-case>
		<description>Verifica se o cliente informado possua parcelas via folha em aberto em uma outra matrícula</description>
		<command>
			<![CDATA[
			
				SELECT CCA.NumMatricula  
				FROM dbo.ParcelamentoCCA P  
				INNER JOIN dbo.ContaCapital CCA ON CCA.NumMatricula = P.NumMatricula 
				WHERE P.CodSituacaoParcela in ( ${COD_PARCELA_GERADA} , ${COD_PARCELA_AGUARDA_RETORNO})  
				AND P.CodModoLanc = ${COD_MODO_LANCAMENTO_VIA_FOLHA} 
				AND P.CodTipoParcelamento =  ${COD_TIPO_PARCELAMENTO_INTEGRAL}  				
				<j:if test="${numCliente != null}">				
					AND CCA.NumCliente =  ${numCliente}
				</j:if>
				<j:if test="${numCliente == null}">				
					AND CCA.NumCliente in (SELECT NumCliente FROM dbo.ContaCapital WHERE NumMatricula = ${numMatricula}) 
				</j:if>
							
			]]>
		</command>
	</query>
	
	<query name="VERIFICARSEPREPREMESSA">
		<use-case name="VERIFICARSEPREPREMESSA"></use-case>
		<description>Verificar se a empresa onde o cooperado trabalha já teve ou não preparação de Remessas</description>
		<command>
			<![CDATA[
			
				SELECT T.NumPessoaJuridica  
				FROM dbo.Trabalha T  
				INNER JOIN dbo.COR_FolhaRemessa FR ON FR.NumPessoaJuridica = T.NumPessoaJuridica  AND AnoRef = ${AnoRef} AND MesRef = ${MesRef} 
				WHERE T.UIDTrabalha = '${UIDTrabalha}'
	
			]]>
		</command>
	</query>
	